In [23]:
import pandas as pd
team_stat = pd.read_csv('tables/team_stat.csv')
match = pd.read_csv('tables/matches.csv')
team_season = pd.read_csv('tables/team_season.csv')
team_stat

,Num_Players,Mins_Per_90_x,season_id,team_id,Squad,league_id,Season_End_Year,Team_or_Opponent,Tkl_Tackles,TklW_Tackles,...,PrgDist_Carries,PrgC_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,PrgR_Receiving,next_season_end,next_season_id
0,32,38,0,102,Alavés,2.0,2020,team,579,346,...,20855,403,307,100,535,309,9525,936,2021,1
1,32,38,0,102,Alavés,2.0,2020,opponent,555,347,...,35364,656,492,146,600,324,15540,1535,2021,1
2,26,38,0,6,Athletic Club,2.0,2020,team,533,324,...,30842,604,493,110,576,299,12422,1273,2021,1
3,26,38,0,6,Athletic Club,2.0,2020,opponent,549,313,...,33686,615,488,106,549,316,13538,1382,2021,1
4,30,38,0,7,Atlético Madrid,2.0,2020,team,658,406,...,30072,598,516,156,586,377,13506,1323,2021,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,35,38,4,80,Sevilla,2.0,2024,opponent,558,347,...,34820,693,492,188,536,362,14675,1469,2025,5
196,29,38,4,91,Valencia,2.0,2024,team,657,379,...,28187,522,399,136,582,318,12130,1151,2025,5
197,29,38,4,91,Valencia,2.0,2024,opponent,612,379,...,35120,621,459,147,635,348,16546,1575,2025,5
198,32,38,4,93,Villarreal,2.0,2024,team,576,348,...,34560,654,491,189,570,356,15179,1548,2025,5
199,32,38,4,93,Villarreal,2.0,2024,opponent,685,436,...,35861,734,573,182,516,316,15513,1644,2025,5

In [3]:
match.drop(['Day', 'Date', 'HomeGoals','AwayGoals','match_id','league_id','Country'], axis=1, inplace=True)
match

,Wk,Time,Home_xG,Away_xG,season_id,home_id,away_id,result,match_key
0,1,21:00,0.5,0.9,0,6,10,1,6_2019-08-16
1,1,17:00,1.6,2.1,0,19,71,2,19_2019-08-17
2,1,19:00,2.3,1.8,0,91,72,x,91_2019-08-17
3,1,20:00,1.6,0.7,0,54,101,1,54_2019-08-17
4,1,21:00,1.4,0.2,0,98,67,2,98_2019-08-17
...,...,...,...,...,...,...,...,...,...
1895,9,14:00,1.0,1.1,4,93,104,2,93_2023-10-08
1896,9,16:15,2.2,1.2,4,7,72,1,7_2023-10-08
1897,9,18:30,1.3,0.9,4,102,12,x,102_2023-10-08
1898,9,18:30,3.1,0.7,4,19,34,x,19_2023-10-08
1899,9,21:00,0.8,3.0,4,100,10,x,100_2023-10-08

In [4]:
data = pd.merge(match,team_stat, left_on=['home_id', 'season_id'], right_on=['team_id', 'next_season_id'], how='left')
data = data[data['Team_or_Opponent']!='opponent']
data.drop(['season_id_y', 'team_id', 'next_season_end', 'next_season_id', 'Team_or_Opponent'], axis=1, inplace=True)
data.rename(columns={'season_id_x': 'season_id'}, inplace=True)
data

,Wk,Time,Home_xG,Away_xG,season_id,home_id,away_id,result,match_key,Num_Players,...,Carries_Carries,TotDist_Carries,PrgDist_Carries,PrgC_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,PrgR_Receiving
0,1,21:00,0.5,0.9,0,6,10,1,6_2019-08-16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,17:00,1.6,2.1,0,19,71,2,19_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,19:00,2.3,1.8,0,91,72,x,91_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,20:00,1.6,0.7,0,54,101,1,54_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,21:00,1.4,0.2,0,98,67,2,98_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3184,9,14:00,1.0,1.1,4,93,104,2,93_2023-10-08,32.0,...,14392.0,81466.0,45470.0,846.0,570.0,239.0,552.0,343.0,16363.0,1617.0
3186,9,16:15,2.2,1.2,4,7,72,1,7_2023-10-08,27.0,...,13702.0,67405.0,35788.0,730.0,473.0,200.0,486.0,277.0,16705.0,1557.0
3188,9,18:30,1.3,0.9,4,102,12,x,102_2023-10-08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3189,9,18:30,3.1,0.7,4,19,34,x,19_2023-10-08,26.0,...,13546.0,71269.0,36623.0,704.0,558.0,161.0,566.0,298.0,14591.0,1393.0
3191,9,21:00,0.8,3.0,4,100,10,x,100_2023-10-08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
team_stat_renamed = team_stat.rename(columns={col: f"{col}_away" for col in team_stat.columns})

In [6]:
data = pd.merge(data,team_stat_renamed, left_on=['away_id', 'season_id'], right_on=['team_id_away', 'next_season_id_away'], how='left')
data = data[data['Team_or_Opponent_away']!='team']
data.drop(['season_id_away', 'team_id_away', 'next_season_end_away', 'next_season_id_away', 'Team_or_Opponent_away'], axis=1, inplace=True)
data.rename(columns={'season_id_x': 'season_id'}, inplace=True)
data

,Wk,Time,Home_xG,Away_xG,season_id,home_id,away_id,result,match_key,Num_Players,...,Carries_Carries_away,TotDist_Carries_away,PrgDist_Carries_away,PrgC_Carries_away,Final_Third_Carries_away,CPA_Carries_away,Mis_Carries_away,Dis_Carries_away,Rec_Receiving_away,PrgR_Receiving_away
0,1,21:00,0.5,0.9,0,6,10,1,6_2019-08-16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,17:00,1.6,2.1,0,19,71,2,19_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,19:00,2.3,1.8,0,91,72,x,91_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,20:00,1.6,0.7,0,54,101,1,54_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,21:00,1.4,0.2,0,98,67,2,98_2019-08-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,9,14:00,1.0,1.1,4,93,104,2,93_2023-10-08,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3185,9,16:15,2.2,1.2,4,7,72,1,7_2023-10-08,27.0,...,10456.0,56751.0,26955.0,575.0,450.0,130.0,558.0,375.0,12005.0,1017.0
3187,9,18:30,1.3,0.9,4,102,12,x,102_2023-10-08,NaN,...,12653.0,68202.0,36566.0,750.0,606.0,147.0,492.0,327.0,14098.0,1553.0
3189,9,18:30,3.1,0.7,4,19,34,x,19_2023-10-08,26.0,...,14675.0,76173.0,38257.0,689.0,544.0,138.0,556.0,256.0,16902.0,1504.0
3191,9,21:00,0.8,3.0,4,100,10,x,100_2023-10-08,NaN,...,9548.0,51240.0,23752.0,474.0,341.0,131.0,517.0,295.0,10223.0,952.0

In [7]:
data.dropna(subset=['Num_Players','Num_Players_away'])

,Wk,Time,Home_xG,Away_xG,season_id,home_id,away_id,result,match_key,Num_Players,...,Carries_Carries_away,TotDist_Carries_away,PrgDist_Carries_away,PrgC_Carries_away,Final_Third_Carries_away,CPA_Carries_away,Mis_Carries_away,Dis_Carries_away,Rec_Receiving_away,PrgR_Receiving_away
381,1,16:00,0.4,0.6,1,101,19,x,101_2020-09-12,26.0,...,11897.0,65184.0,33444.0,679.0,537.0,148.0,511.0,338.0,13334.0,1423.0
383,1,18:30,0.4,0.5,1,100,6,1,100_2020-09-12,27.0,...,12428.0,65062.0,33686.0,615.0,488.0,106.0,549.0,316.0,13538.0,1382.0
387,1,14:00,1.2,0.4,1,102,12,2,102_2020-09-13,32.0,...,10260.0,56375.0,28957.0,613.0,438.0,180.0,466.0,280.0,11524.0,1250.0
389,1,16:00,0.8,0.3,1,92,72,x,92_2020-09-13,30.0,...,10620.0,55968.0,26544.0,546.0,441.0,158.0,539.0,299.0,11562.0,1117.0
392,1,21:00,1.9,2.0,1,91,99,1,91_2020-09-13,28.0,...,12480.0,66807.0,34969.0,741.0,557.0,219.0,549.0,303.0,13726.0,1485.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3178,9,16:15,3.2,0.5,4,71,67,1,71_2023-10-07,26.0,...,12906.0,68441.0,35932.0,680.0,486.0,170.0,586.0,268.0,14007.0,1357.0
3180,9,18:30,0.6,0.5,4,54,91,x,54_2023-10-07,31.0,...,11306.0,59758.0,29191.0,480.0,379.0,117.0,545.0,367.0,12455.0,1209.0
3182,9,21:00,1.0,1.0,4,80,70,x,80_2023-10-07,35.0,...,11197.0,60030.0,30078.0,589.0,432.0,165.0,594.0,355.0,12797.0,1222.0
3185,9,16:15,2.2,1.2,4,7,72,1,7_2023-10-08,27.0,...,10456.0,56751.0,26955.0,575.0,450.0,130.0,558.0,375.0,12005.0,1017.0
3189,9,18:30,3.1,0.7,4,19,34,x,19_2023-10-08,26.0,...,14675.0,76173.0,38257.0,689.0,544.0,138.0,556.0,256.0,16902.0,1504.0

In [8]:
for col in data.columns:
    print(col, type(col[0]))

Wk <class 'str'>
Time <class 'str'>
Home_xG <class 'str'>
Away_xG <class 'str'>
season_id <class 'str'>
home_id <class 'str'>
away_id <class 'str'>
result <class 'str'>
match_key <class 'str'>
Num_Players <class 'str'>
Mins_Per_90_x <class 'str'>
Squad <class 'str'>
league_id <class 'str'>
Season_End_Year <class 'str'>
Tkl_Tackles <class 'str'>
TklW_Tackles <class 'str'>
Def 3rd_Tackles <class 'str'>
Mid 3rd_Tackles <class 'str'>
Att 3rd_Tackles <class 'str'>
Tkl_Challenges <class 'str'>
Att_Challenges <class 'str'>
Tkl_percent_Challenges <class 'str'>
Lost_Challenges <class 'str'>
Blocks_Blocks <class 'str'>
Sh_Blocks <class 'str'>
Pass_Blocks <class 'str'>
Int <class 'str'>
Tkl_plus_Int <class 'str'>
Clr <class 'str'>
Err <class 'str'>
SCA_SCA <class 'str'>
SCA90_SCA <class 'str'>
PassLive_SCA_Types <class 'str'>
PassDead_SCA_Types <class 'str'>
TO_SCA_Types <class 'str'>
Sh_SCA_Types <class 'str'>
Fld_SCA_Types <class 'str'>
Def_SCA_Types <class 'str'>
GCA_GCA <class 'str'>
GCA90_GCA <class 'str'>
PassLive_GCA_Types <class 'str'>
PassDead_GCA_Types <class 'str'>
TO_GCA_Types <class 'str'>
Sh_GCA_Types <class 'str'>
Fld_GCA_Types <class 'str'>
Def_GCA_Types <class 'str'>
Competition_Name <class 'str'>
Gender <class 'str'>
Country <class 'str'>
MP_Playing_Time <class 'str'>
Starts_Playing_Time <class 'str'>
Min_Playing_Time <class 'str'>
Mins_Per_90_Playing_Time <class 'str'>
GA <class 'str'>
GA90 <class 'str'>
SoTA <class 'str'>
Saves <class 'str'>
Save_percent <class 'str'>
W <class 'str'>
D <class 'str'>
L <class 'str'>
CS <class 'str'>
CS_percent <class 'str'>
PKatt_Penalty_Kicks <class 'str'>
PKA_Penalty_Kicks <class 'str'>
PKsv_Penalty_Kicks <class 'str'>
PKm_Penalty_Kicks <class 'str'>
Save_percent_Penalty_Kicks <class 'str'>
GA_Goals <class 'str'>
PKA_Goals <class 'str'>
FK_Goals <class 'str'>
CK_Goals <class 'str'>
OG_Goals <class 'str'>
PSxG_Expected <class 'str'>
PSxG_per_SoT_Expected <class 'str'>
PSxGPlus_Minus_Expected <class 'str'>
_per_90_Expected <class 'str'>
Cmp_Launched <class 'str'>
Att_Launched <class 'str'>
Cmp_percent_Launched <class 'str'>
Att (GK)_Passes <class 'str'>
Thr_Passes <class 'str'>
Launch_percent_Passes <class 'str'>
AvgLen_Passes <class 'str'>
Att_Goal_Kicks <class 'str'>
Launch_percent_Goal_Kicks <class 'str'>
AvgLen_Goal_Kicks <class 'str'>
Opp_Crosses <class 'str'>
Stp_Crosses <class 'str'>
Stp_percent_Crosses <class 'str'>
#OPA_Sweeper <class 'str'>
#OPA_per_90_Sweeper <class 'str'>
AvgDist_Sweeper <class 'str'>
Mins_Per_90_y <class 'str'>
Gls_Standard <class 'str'>
Sh_Standard <class 'str'>
SoT_Standard <class 'str'>
SoT_percent_Standard <class 'str'>
Sh_per_90_Standard <class 'str'>
SoT_per_90_Standard <class 'str'>
G_per_Sh_Standard <class 'str'>
G_per_SoT_Standard <class 'str'>
Dist_Standard <class 'str'>
FK_Standard <class 'str'>
PK_Standard <class 'str'>
PKatt_Standard <class 'str'>
xG_Expected <class 'str'>
npxG_Expected <class 'str'>
npxG_per_Sh_Expected <class 'str'>
G_minus_xG_Expected <class 'str'>
np:G_minus_xG_Expected <class 'str'>
Cmp_Total <class 'str'>
Att_Total <class 'str'>
Cmp_percent_Total <class 'str'>
TotDist_Total <class 'str'>
PrgDist_Total <class 'str'>
Cmp_Short <class 'str'>
Att_Short <class 'str'>
Cmp_percent_Short <class 'str'>
Cmp_Medium <class 'str'>
Att_Medium <class 'str'>
Cmp_percent_Medium <class 'str'>
Cmp_Long <class 'str'>
Att_Long <class 'str'>
Cmp_percent_Long <class 'str'>
Ast <class 'str'>
xAG <class 'str'>
xA_Expected <class 'str'>
A_minus_xAG_Expected <class 'str'>
KP <class 'str'>
Final_Third <class 'str'>
PPA <class 'str'>
CrsPA <class 'str'>
PrgP <class 'str'>
Att <class 'str'>
Live_Pass_Types <class 'str'>
Dead_Pass_Types <class 'str'>
FK_Pass_Types <class 'str'>
TB_Pass_Types <class 'str'>
Sw_Pass_Types <class 'str'>
Crs_Pass_Types <class 'str'>
TI_Pass_Types <class 'str'>
CK_Pass_Types <class 'str'>
In_Corner_Kicks <class 'str'>
Out_Corner_Kicks <class 'str'>
Str_Corner_Kicks <class 'str'>
Cmp_Outcomes <class 'str'>
Off_Outcomes <class 'str'>
Blocks_Outcomes <class 'str'>
Poss <class 'str'>
Touches_Touches <class 'str'>
Def Pen_Touches <class 'str'>
Def 3rd_Touches <class 'str'>
Mid 3rd_Touches <class 'str'>
Att 3rd_Touches <class 'str'>
Att Pen_Touches <class 'str'>
Live_Touches <class 'str'>
Att_Take_Ons <class 'str'>
Succ_Take_Ons <class 'str'>
Succ_percent_Take_Ons <class 'str'>
Tkld_Take_Ons <class 'str'>
Tkld_percent_Take_Ons <class 'str'>
Carries_Carries <class 'str'>
TotDist_Carries <class 'str'>
PrgDist_Carries <class 'str'>
PrgC_Carries <class 'str'>
Final_Third_Carries <class 'str'>
CPA_Carries <class 'str'>
Mis_Carries <class 'str'>
Dis_Carries <class 'str'>
Rec_Receiving <class 'str'>
PrgR_Receiving <class 'str'>
Num_Players_away <class 'str'>
Mins_Per_90_x_away <class 'str'>
Squad_away <class 'str'>
league_id_away <class 'str'>
Season_End_Year_away <class 'str'>
Tkl_Tackles_away <class 'str'>
TklW_Tackles_away <class 'str'>
Def 3rd_Tackles_away <class 'str'>
Mid 3rd_Tackles_away <class 'str'>
Att 3rd_Tackles_away <class 'str'>
Tkl_Challenges_away <class 'str'>
Att_Challenges_away <class 'str'>
Tkl_percent_Challenges_away <class 'str'>
Lost_Challenges_away <class 'str'>
Blocks_Blocks_away <class 'str'>
Sh_Blocks_away <class 'str'>
Pass_Blocks_away <class 'str'>
Int_away <class 'str'>
Tkl_plus_Int_away <class 'str'>
Clr_away <class 'str'>
Err_away <class 'str'>
SCA_SCA_away <class 'str'>
SCA90_SCA_away <class 'str'>
PassLive_SCA_Types_away <class 'str'>
PassDead_SCA_Types_away <class 'str'>
TO_SCA_Types_away <class 'str'>
Sh_SCA_Types_away <class 'str'>
Fld_SCA_Types_away <class 'str'>
Def_SCA_Types_away <class 'str'>
GCA_GCA_away <class 'str'>
GCA90_GCA_away <class 'str'>
PassLive_GCA_Types_away <class 'str'>
PassDead_GCA_Types_away <class 'str'>
TO_GCA_Types_away <class 'str'>
Sh_GCA_Types_away <class 'str'>
Fld_GCA_Types_away <class 'str'>
Def_GCA_Types_away <class 'str'>
Competition_Name_away <class 'str'>
Gender_away <class 'str'>
Country_away <class 'str'>
MP_Playing_Time_away <class 'str'>
Starts_Playing_Time_away <class 'str'>
Min_Playing_Time_away <class 'str'>
Mins_Per_90_Playing_Time_away <class 'str'>
GA_away <class 'str'>
GA90_away <class 'str'>
SoTA_away <class 'str'>
Saves_away <class 'str'>
Save_percent_away <class 'str'>
W_away <class 'str'>
D_away <class 'str'>
L_away <class 'str'>
CS_away <class 'str'>
CS_percent_away <class 'str'>
PKatt_Penalty_Kicks_away <class 'str'>
PKA_Penalty_Kicks_away <class 'str'>
PKsv_Penalty_Kicks_away <class 'str'>
PKm_Penalty_Kicks_away <class 'str'>
Save_percent_Penalty_Kicks_away <class 'str'>
GA_Goals_away <class 'str'>
PKA_Goals_away <class 'str'>
FK_Goals_away <class 'str'>
CK_Goals_away <class 'str'>
OG_Goals_away <class 'str'>
PSxG_Expected_away <class 'str'>
PSxG_per_SoT_Expected_away <class 'str'>
PSxGPlus_Minus_Expected_away <class 'str'>
_per_90_Expected_away <class 'str'>
Cmp_Launched_away <class 'str'>
Att_Launched_away <class 'str'>
Cmp_percent_Launched_away <class 'str'>
Att (GK)_Passes_away <class 'str'>
Thr_Passes_away <class 'str'>
Launch_percent_Passes_away <class 'str'>
AvgLen_Passes_away <class 'str'>
Att_Goal_Kicks_away <class 'str'>
Launch_percent_Goal_Kicks_away <class 'str'>
AvgLen_Goal_Kicks_away <class 'str'>
Opp_Crosses_away <class 'str'>
Stp_Crosses_away <class 'str'>
Stp_percent_Crosses_away <class 'str'>
#OPA_Sweeper_away <class 'str'>
#OPA_per_90_Sweeper_away <class 'str'>
AvgDist_Sweeper_away <class 'str'>
Mins_Per_90_y_away <class 'str'>
Gls_Standard_away <class 'str'>
Sh_Standard_away <class 'str'>
SoT_Standard_away <class 'str'>
SoT_percent_Standard_away <class 'str'>
Sh_per_90_Standard_away <class 'str'>
SoT_per_90_Standard_away <class 'str'>
G_per_Sh_Standard_away <class 'str'>
G_per_SoT_Standard_away <class 'str'>
Dist_Standard_away <class 'str'>
FK_Standard_away <class 'str'>
PK_Standard_away <class 'str'>
PKatt_Standard_away <class 'str'>
xG_Expected_away <class 'str'>
npxG_Expected_away <class 'str'>
npxG_per_Sh_Expected_away <class 'str'>
G_minus_xG_Expected_away <class 'str'>
np:G_minus_xG_Expected_away <class 'str'>
Cmp_Total_away <class 'str'>
Att_Total_away <class 'str'>
Cmp_percent_Total_away <class 'str'>
TotDist_Total_away <class 'str'>
PrgDist_Total_away <class 'str'>
Cmp_Short_away <class 'str'>
Att_Short_away <class 'str'>
Cmp_percent_Short_away <class 'str'>
Cmp_Medium_away <class 'str'>
Att_Medium_away <class 'str'>
Cmp_percent_Medium_away <class 'str'>
Cmp_Long_away <class 'str'>
Att_Long_away <class 'str'>
Cmp_percent_Long_away <class 'str'>
Ast_away <class 'str'>
xAG_away <class 'str'>
xA_Expected_away <class 'str'>
A_minus_xAG_Expected_away <class 'str'>
KP_away <class 'str'>
Final_Third_away <class 'str'>
PPA_away <class 'str'>
CrsPA_away <class 'str'>
PrgP_away <class 'str'>
Att_away <class 'str'>
Live_Pass_Types_away <class 'str'>
Dead_Pass_Types_away <class 'str'>
FK_Pass_Types_away <class 'str'>
TB_Pass_Types_away <class 'str'>
Sw_Pass_Types_away <class 'str'>
Crs_Pass_Types_away <class 'str'>
TI_Pass_Types_away <class 'str'>
CK_Pass_Types_away <class 'str'>
In_Corner_Kicks_away <class 'str'>
Out_Corner_Kicks_away <class 'str'>
Str_Corner_Kicks_away <class 'str'>
Cmp_Outcomes_away <class 'str'>
Off_Outcomes_away <class 'str'>
Blocks_Outcomes_away <class 'str'>
Poss_away <class 'str'>
Touches_Touches_away <class 'str'>
Def Pen_Touches_away <class 'str'>
Def 3rd_Touches_away <class 'str'>
Mid 3rd_Touches_away <class 'str'>
Att 3rd_Touches_away <class 'str'>
Att Pen_Touches_away <class 'str'>
Live_Touches_away <class 'str'>
Att_Take_Ons_away <class 'str'>
Succ_Take_Ons_away <class 'str'>
Succ_percent_Take_Ons_away <class 'str'>
Tkld_Take_Ons_away <class 'str'>
Tkld_percent_Take_Ons_away <class 'str'>
Carries_Carries_away <class 'str'>
TotDist_Carries_away <class 'str'>
PrgDist_Carries_away <class 'str'>
PrgC_Carries_away <class 'str'>
Final_Third_Carries_away <class 'str'>
CPA_Carries_away <class 'str'>
Mis_Carries_away <class 'str'>
Dis_Carries_away <class 'str'>
Rec_Receiving_away <class 'str'>
PrgR_Receiving_away <class 'str'>

In [17]:
data.drop(['season_id', 'match_key', 'Squad', 'league_id', 'Squad_away', 'league_id_away', 'Season_End_Year', 'Season_End_Year_away', 'Time', 'Home_xG', 'Away_xG'], axis=1, inplace=True)

In [21]:
data

,Wk,home_id,away_id,result,Num_Players,Mins_Per_90_x,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,...,Carries_Carries_away,TotDist_Carries_away,PrgDist_Carries_away,PrgC_Carries_away,Final_Third_Carries_away,CPA_Carries_away,Mis_Carries_away,Dis_Carries_away,Rec_Receiving_away,PrgR_Receiving_away
0,1,6,10,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,19,71,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,91,72,x,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,54,101,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,98,67,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,9,93,104,2,32.0,38.0,578.0,370.0,276.0,201.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3185,9,7,72,1,27.0,38.0,667.0,408.0,332.0,245.0,...,10456.0,56751.0,26955.0,575.0,450.0,130.0,558.0,375.0,12005.0,1017.0
3187,9,102,12,x,NaN,NaN,NaN,NaN,NaN,NaN,...,12653.0,68202.0,36566.0,750.0,606.0,147.0,492.0,327.0,14098.0,1553.0
3189,9,19,34,x,26.0,38.0,664.0,413.0,319.0,269.0,...,14675.0,76173.0,38257.0,689.0,544.0,138.0,556.0,256.0,16902.0,1504.0
3191,9,100,10,x,NaN,NaN,NaN,NaN,NaN,NaN,...,9548.0,51240.0,23752.0,474.0,341.0,131.0,517.0,295.0,10223.0,952.0

In [29]:
data.to_csv('tables/data.csv', index=False)

In [5]:
data = pd.read_csv('tables/data.csv')